name: Build and test Go package

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Checkout
      uses: actions/checkout@v4

    - name: Fetch dependencies
      run: go mod tidy

    - name: Run Go tests
      run: go test ./...